// <auto-generated />
namespace BlogSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class yuanhui201910291322 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yuanhui201910291322));
        
        string IMigrationMetadata.Id
        {
            get { return "201910290522482_yuanhui201910291322"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
