// <auto-generated />
namespace BlogSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class yuanhui2019116 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yuanhui2019116));
        
        string IMigrationMetadata.Id
        {
            get { return "201911061317028_yuanhui2019116"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
